# Generated by Django 4.0.5 on 2022-06-04 11:15

from django.db import migrations, models
import django.db.models.deletion
import scrapping_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scrapping_app.models.default_urls)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.city', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.language', verbose_name='Язык программирования')),
            ],
        ),
        migrations.AddConstraint(
            model_name='url',
            constraint=models.UniqueConstraint(fields=('city', 'language'), name='unique_search'),
        ),
    ]
